((emacs-lisp-mode . ((fill-column . 100)
                     (indent-tabs-mode . nil)
                     (lisp-indent-function . common-lisp-indent-function)
                     (sentence-end-double-space . nil)
                     (elisp-lint-indent-specs . ((describe . 1)
                                                 (it . 1))))))
